#!/bin/bash

function system()
{
    sudo apt install docker.io npm sshpass fzf -y

    # https://www.kali.org/docs/containers/installing-docker-on-kali
    # Add myself to docker group to not use sudo
    # Looks like you gotta restart machine
    sudo usermod -aG docker $(whoami)
}

function nvim()
{
    local packerpath="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"

    if [[ -d "$packerpath" ]]; then
        echo "packer: already installed"
    else
        git clone --depth 1 https://github.com/wbthomason/packer.nvim "$packerpath"
    fi
}

function tmux()
{
    local tpmpath="$XDG_CONFIG_HOME/tmux/plugins/tpm"
    git clone https://github.com/tmux-plugins/tpm "$tpmpath"

    # restore by default tmux session setup
    mkdir -p "$HOME/.local/share/tmux/resurrect"
    cp tmux/tmux_resurrect_20240313T100900.txt ~/.local/share/tmux/resurrect
    rm ~/.local/share/tmux/resurrect/last
    ln -s ~/.dotfiles/tmux/tmux_resurrect_20240313T100900.txt ~/.local/share/tmux/resurrect/last
}

system
nvim
tmux
