#!/bin/bash

SYSCMDS="stow lua nvim git"

function syscheck()
{
    local checkflag=true

    echo "Utils missing on the system:"
    for util in ${SYSCMDS[@]}; do
        which -s "$util"
        if [[ $? -ne 0 ]]; then
            echo " * $util"
            checkflag=false
        fi
    done
    if [[ "$checkflag" == true ]]; then
        printf "  None\n\n"
        exit 0
    fi
    exit 1
}

syscheck
